apiVersion: apps/v1
kind: Deployment
metadata:
  name: batmanapi-${DEPLOY_ENV}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batmanapi-${DEPLOY_ENV}
  template:
    metadata:
      labels:
        app: batmanapi-${DEPLOY_ENV}
    spec:
      containers:
      - name: batmanapi
        image: docker.io/library/batmanapi:${IMAGE_VERSION}
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: batmansvc-${DEPLOY_ENV}
spec:
  type: NodePort
  selector:
    app: batmanapi-${DEPLOY_ENV}
  ports:
  - protocol: TCP
    port: ${NODE_PORT}
    targetPort: 5000