apiVersion: apps/v1
kind: Deployment
metadata:
  name: batmanapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: batmanapi
  template:
    metadata:
      labels:
        app: batmanapi
    spec:
      containers:
      - name: batmanapi
        image: docker.io/library/batmanapi:1.0
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: batmansvc
spec:
  type: NodePort
  selector:
    app: batmanapi
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000